zuul:
  # Using this approach gets me /one/nested properly
  # but not /one
#  ignoredPatterns: /one/**
  routes:
    # Using this pattern breaks both /one/nested and /one
    one:
      path: /one/**
      url: forward:/one
    legacy:
      path: /**
      url: http://localhost:9090
